FROM python:3.11

WORKDIR /app

RUN pip install llama-cpp-python fastapi uvicorn pydantic

COPY mistral_server.py /app/
COPY mistralQ2_K.gguf /app/

EXPOSE 9001

ENTRYPOINT ["uvicorn", "mistral_server:app_nlp", "--host", "0.0.0.0", "--port", "9001"]
