version: '3'
services:
  mistral_server:
    build:
      context: .
      dockerfile: Dockerfile_mistral_server
    ports:
      - "9001:9001"
    depends_on:
      - llama_cpp

  manager:
    build:
      context: .
      dockerfile: Dockerfile_manager
    ports:
      - "8000:8000"
    depends_on:
      - llama_cpp

  llama_cpp:
    image: python:3.11
    command: tail -f /dev/null

  external_service:
  # docker run -d -p 9000:9000 -e ASR_MODEL=base -e ASR_ENGINE=openai_whisper
    image: onerahmet/openai-whisper-asr-webservice:latest
    ports:
      - "9000:9000"