FROM tiangolo/uvicorn-gunicorn-fastapi:python3.11

WORKDIR /app

RUN pip install requests

COPY manager.py /app/

EXPOSE 8000

ENTRYPOINT ["uvicorn", "manager:app_manager", "--host", "0.0.0.0", "--port", "8000"]
