# Generated by Django 5.0.4 on 2024-04-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("username", models.CharField(max_length=64, unique=True)),
                ("password", models.CharField(max_length=128)),
            ],
        ),
    ]
