# Generated by Django 5.0.4 on 2024-04-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="id",
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
